import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function About() {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name='author' content='MDIA 2109'/>
        <meta property='og:title' content='Assignment #1 - About Us Page'/>
        <meta property='og:description' content='BCIT Digital Design and Development Diploma'/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
            <div>
                <h1></h1>
                <h1></h1>

                <p></p>
                <p></p>
                <p></p>
                <p></p>
                <p></p>
                <p></p>
                <p></p>

                <h2></h2>
                <h2></h2>
                <h3></h3>

                <div className={styles.carousel} id='carouselImage'>
                    <div className={styles.carouseltext} id='testOnImageHere'></div>
                    <ul>
                        <li>Applied & Natural Sciences</li>
                        <li>Business & Media</li>
                        <li>Computing & IT</li>
                        <li>Engineerin</li>
                        <li>Health Sciences</li>
                        <li>Trades & Apprenticeships</li>
                    </ul>
                </div>
            </div>

            <div>
                <a><span><img src='/icons/upwardArrow.png'/></span></a>
                <a><span><img src='/icons/downwardArrow.png'/></span></a>
            </div>
      </main>
    </>
  )
}