import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact Us</title>
        <meta name='author' content='MDIA 2109'/>
        <meta property='og:title' content='Assignment #1 - Contact Us Page'/>
        <meta property='og:description' content='BCIT Digital Design and Development Diploma'/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
        <div>
            <h1></h1>
        </div>
        <div>
            <p></p>
            <form>            
                <fieldset>
                    <table>
                        <thead><tr></tr><tr></tr></thead>
                        <thead></thead>
                    </table>
                </fieldset>
                <button></button>
            </form>
        </div>
        <div>
            <a><span><img src='/icons/upwardArrow.png'/></span></a>
        </div>
      </main>
    </>
  )
}
